openapi: 3.0.3
info:
  title: Favaa Api Spesification
  description: Favaa Api Spesification
  version: 1.0.0
servers:
  - url: 'http://localhost:8000/api'
    description: Development mitra_server
  - url: 'https//favaa-mitra_server.com/api/v1'
    description: Production mitra_server
paths:
  /register":
    description:

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          required: true

        name:
          type: string
        email:
          type: string
        password:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      description: user schemas
  examples:
    User:
      value:
        id: 1
        name: "John Doe"
        email: "asdfasf@gmail.com"
        password: "123456"
        created_at: "2021-01-01 00:00:00"
        updated_at: "2021-01-01 00:00:00"



  
